/* tslint:disable */
/* eslint-disable */
/**
 * Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * The response from the AI assistant
 * @export
 * @interface ChatResponse
 */
export interface ChatResponse {
    /**
     * The text response generated by the chatbot
     * @type {string}
     * @memberof ChatResponse
     */
    answer: string;
    /**
     * A list of products recommended by the assistant, if any
     * @type {Array<Product>}
     * @memberof ChatResponse
     */
    recommendedProducts: Array<Product>;
}

/**
 * Check if a given object implements the ChatResponse interface.
 */
export function instanceOfChatResponse(value: object): value is ChatResponse {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    if (!('recommendedProducts' in value) || value['recommendedProducts'] === undefined) return false;
    return true;
}

export function ChatResponseFromJSON(json: any): ChatResponse {
    return ChatResponseFromJSONTyped(json, false);
}

export function ChatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'recommendedProducts': ((json['recommendedProducts'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ChatResponseToJSON(json: any): ChatResponse {
    return ChatResponseToJSONTyped(json, false);
}

export function ChatResponseToJSONTyped(value?: ChatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'recommendedProducts': ((value['recommendedProducts'] as Array<any>).map(ProductToJSON)),
    };
}

