spring:
  application:
    name: ai-reco-poc
  # Temporary removed
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      chroma:
        collection-name: products
        initialize-schema: true
        client:
          host: http://localhost
          port: 8444

dataLoader:
  inputFile: "data/products.json"

server:
  port: 9944
