/* tslint:disable */
/* eslint-disable */
/**
 * Product API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Product,
  SearchRequest,
} from '../models/index';
import {
    ProductFromJSON,
    ProductToJSON,
    SearchRequestFromJSON,
    SearchRequestToJSON,
} from '../models/index';

export interface GetProductRecommendationsRequest {
    searchRequest: SearchRequest;
}

/**
 * ProductRecommendationApi - interface
 * 
 * @export
 * @interface ProductRecommendationApiInterface
 */
export interface ProductRecommendationApiInterface {
    /**
     * 
     * @summary Recommend products
     * @param {SearchRequest} searchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductRecommendationApiInterface
     */
    getProductRecommendationsRaw(requestParameters: GetProductRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Product>>>;

    /**
     * Recommend products
     */
    getProductRecommendations(requestParameters: GetProductRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Product>>;

}

/**
 * 
 */
export class ProductRecommendationApi extends runtime.BaseAPI implements ProductRecommendationApiInterface {

    /**
     * Recommend products
     */
    async getProductRecommendationsRaw(requestParameters: GetProductRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Product>>> {
        if (requestParameters['searchRequest'] == null) {
            throw new runtime.RequiredError(
                'searchRequest',
                'Required parameter "searchRequest" was null or undefined when calling getProductRecommendations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/products/recommend`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRequestToJSON(requestParameters['searchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductFromJSON));
    }

    /**
     * Recommend products
     */
    async getProductRecommendations(requestParameters: GetProductRecommendationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Product>> {
        const response = await this.getProductRecommendationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
