version: '3.8'
services:
  chroma:
    image: chromadb/chroma:1.0.21.dev43
    container_name: chroma-db
    ports:
      - "8444:8000"
    volumes:
      - chromadata:/data

# You could create different volumes for working with different LLMMs
volumes:
  chromadata: